### ISSUE TITLE
Add disclaimer to app

### ISSUE THREAD

**Issue by lynguyen11** [mvhs-apps/mvhs-app-pwa#10]
The information may not be fully accurate or finalized due to various unforeseen reasons.  It is important to double check with the school website for the official school related information.

**Comment by mbacvanski** [comment]
Should go right underneath the `CalendarContainer` in `src/components/SchedulePageContainer.js`

https://github.com/mvhs-apps/mvhs-app-pwa/blob/master/src/components/SchedulePage.js

**Comment by plusCubed** [comment]
Done.
