### ISSUE TITLE
When waking on no internet connection, schedule displays `TypeError: Failed to Fetch`

### ISSUE THREAD

**Issue by mbacvanski** [mvhs-apps/mvhs-app-pwa#27]
![image](https://user-images.githubusercontent.com/7774585/29750936-5f7c0c88-8afd-11e7-9f86-bb5c6607d2bb.png)

When the computer wakes up without an internet connection.

**Comment by plusCubed** [comment]
Steps to reproduce?

**Comment by mbacvanski** [comment]
1. Open mvhacks.io
1. Suspend computer
1. Wait 8.7 hours
1. Wake computer but knowing Linux it will take a minute or so to reconnect to wifi 
1. ....
1. ....
1. Profit??!

**Comment by AlexJVG** [comment]
<img width="1440" alt="screen shot 2017-08-30 at 9 24 02 am" src="https://user-images.githubusercontent.com/30816242/29884064-13850746-8d67-11e7-9957-98dd1bc7f14f.png">

I got the same problem from except for the bell schedule showed, but not the school events.

**Comment by lynguyen11** [comment]
I am also having the same problem when offline with my android phone today.
![screenshot_20170908-075844](https://user-images.githubusercontent.com/8756775/30217746-f5375cec-946b-11e7-8cec-2c5b2efc5ab3.png)

.  Mr. Nguyen

**Comment by plusCubed** [comment]
I can't seem to find a way to reproduce, even on the old version, but this _should_ be fixed.

**Comment by mbacvanski** [comment]
I just got it a few days ago, but when I reloaded the page it resolved itself .. :thinking:

**Comment by mbacvanski** [comment]
Reopening only if we can find a way to reproduce consistently.
