### ISSUE TITLE
Search bug 🤔

### ISSUE THREAD

**Issue by mbacvanski** [mvhs-apps/mvhs-app-pwa#39]
![image](https://user-images.githubusercontent.com/7774585/33384828-eec3671a-d4db-11e7-895d-1022e6bb5dbb.png)
![image](https://user-images.githubusercontent.com/7774585/33384837-f3ffc160-d4db-11e7-9034-794e7e5d2f30.png)

**Comment by lynguyen11** [comment]
Please see this example for a possible fix.

https://stackblitz.com/edit/firebase-read-location-example

Mr. Nguyen

**Comment by plusCubed** [comment]
Fixed in #41
