### ISSUE TITLE
Investigate possibility of lunch menu

### ISSUE THREAD

**Issue by plusCubed** [mvhs-apps/mvhs-app-pwa#4]
@mbacvanski mentioned there was a mailing list...

**Comment by mbacvanski** [comment]
The MVLA Food Service posts monthly menus [here](http://mvlafoodservice.com/index.php?page=menus&sm=8&sy=2017&sid=1908131605284815#clicktoscroll). I don't think there's an easy way to get the menu items.

[Here's](https://www.schoolnutritionandfitness.com/webmenus2/#/view?id=5903790ceabc88c8388b456a&siteCode=1827) an example of one month.

**Comment by plusCubed** [comment]
Good to know. If someone wants to implement a scraper go for it, but I think a link/iframe is good enough.
