### ISSUE TITLE
"Not sure what a schedule A means"

### ISSUE THREAD

**Issue by mbacvanski** [mvhs-apps/mvhs-app-pwa#46]
![image](https://user-images.githubusercontent.com/7774585/63282545-e4577b00-c263-11e9-814b-ce65153315f2.png)

> nOt SuRe WhAt A sChEdUlE A mEaNs

**Comment by lynguyen11** [comment]
Seems like that is problem with the school's google web calendar in its
description and not the app.
[image: image.png]

**Comment by lynguyen11** [comment]
[image: image.png]
