### ISSUE TITLE
add a static version of the school map

### ISSUE THREAD

**Issue by lynguyen11** [mvhs-apps/mvhs-app-pwa#5]
static version of the school map.  No need for Navigation or Google Maps.
- for example: if the user search for something, it will circle or pin to the location on the map.   if the user search for "Lost and Found", then the Administration Building will be marked or highlighted.

**Comment by igrowsquareroots** [comment]
What file did you put in?

**Comment by mbacvanski** [comment]
@igrowsquareroots [School Map 2017-2018 - COLORED.pdf](https://github.com/mvhs-apps/mvhs-app-pwa/files/1219845/School.Map.2017-2018.-.COLORED.pdf)

**Comment by mbacvanski** [comment]
![image](https://user-images.githubusercontent.com/7774585/29257084-fe170e0a-8063-11e7-800b-492444d08551.png)

**Comment by igrowsquareroots** [comment]
Fixed
